// ============================================
// DATA.JS - Auto-generated by GFFI Live Calculator
// Last Updated: 2026-03-20 01:54:44
// ============================================
// NOTE: Only real data is included. No default values.

const countryData = [
  {
    "flag": "🇸🇬",
    "name": "Singapore",
    "gffi": 420.6,
    "status": "critical"
  }
];

const globalGFFI = 420.6;

const updateDate = '20 Mar 2026';
const updateTime = '01:54 AM';

const sectorData = [];

const stockPicks = {};

const indiaMarketData = {};