// ============================================
// DATA.JS - Auto-generated by GFFI Daily Calculator
// Last Updated: 2026-04-09 22:41:44
// ============================================
// CAPITAL DATA SOURCES:
//   • FRED (REAL): 0 countries
//   • Proxy (volatility-based): 1 countries
// ============================================

const countryData = [
  {
    "flag": "🇸🇬",
    "name": "Singapore",
    "gffi": 53.7,
    "status": "success",
    "entropy": 0.8,
    "capital": 14.91,
    "capital_source": "PROXY"
  }
];

const globalGFFI = 53.7;

const updateDate = '09 Apr 2026';
const updateTime = '10:41 PM';

// Empty arrays for removed features
const sectorData = [];
const stockPicks = {};

const indiaMarketData = {
    'nifty': 0,
    'sensex': 0,
    'nifty_change': 0,
    'sensex_change': 0,
    'india_gffi': 60
};