// ============================================
// DATA.JS - Auto-generated by GFFI Live Calculator
// Last Updated: 2026-03-25 23:37:19
// ============================================
// FIXED VERSION - Corrected entropy and capital calculations

const countryData = [
  {
    "flag": "🇮🇳",
    "name": "India",
    "gffi": 37.5,
    "status": "success"
  }
];

const globalGFFI = 37.5;

const updateDate = '25 Mar 2026';
const updateTime = '11:37 PM';

const sectorData = [
  {
    "name": "Banking",
    "gffi": 37.5,
    "trend": "down",
    "stocks": [
      "HDFCBANK",
      "ICICIBANK",
      "SBIN"
    ]
  },
  {
    "name": "IT",
    "gffi": 37.6,
    "trend": "down",
    "stocks": [
      "TCS",
      "INFY"
    ]
  },
  {
    "name": "Pharma",
    "gffi": 35.7,
    "trend": "down",
    "stocks": [
      "SUNPHARMA"
    ]
  },
  {
    "name": "Auto",
    "gffi": 38.3,
    "trend": "down",
    "stocks": [
      "MARUTI"
    ]
  },
  {
    "name": "FMCG",
    "gffi": 36.9,
    "trend": "down",
    "stocks": [
      "HINDUNILVR",
      "ITC",
      "TITAN"
    ]
  },
  {
    "name": "Energy",
    "gffi": 36.7,
    "trend": "down",
    "stocks": [
      "RELIANCE",
      "ONGC",
      "NTPC"
    ]
  },
  {
    "name": "Telecom",
    "gffi": 36.4,
    "trend": "down",
    "stocks": [
      "BHARTIARTL"
    ]
  },
  {
    "name": "Construction",
    "gffi": 41.2,
    "trend": "down",
    "stocks": [
      "LT"
    ]
  }
];

const stockPicks = {
  "safe": [
    {
      "symbol": "ITC",
      "name": "ITC Ltd",
      "gffi": 36.2,
      "action": "BUY",
      "reason": "Low GFFI indicates stability at ₹295.75"
    },
    {
      "symbol": "RELIANCE",
      "name": "Reliance Industries",
      "gffi": 36.4,
      "action": "BUY",
      "reason": "Low GFFI indicates stability at ₹1412.55"
    },
    {
      "symbol": "ICICIBANK",
      "name": "ICICI Bank",
      "gffi": 36.8,
      "action": "BUY",
      "reason": "Low GFFI indicates stability at ₹1259.8"
    }
  ],
  "risky": [
    {
      "symbol": "HDFCBANK",
      "name": "HDFC Bank",
      "gffi": 38.1,
      "action": "SELL",
      "reason": "High GFFI indicates risk at ₹781.7"
    },
    {
      "symbol": "SBIN",
      "name": "State Bank of India",
      "gffi": 37.5,
      "action": "SELL",
      "reason": "High GFFI indicates risk at ₹1060.55"
    },
    {
      "symbol": "TCS",
      "name": "Tata Consultancy Services",
      "gffi": 37.2,
      "action": "SELL",
      "reason": "High GFFI indicates risk at ₹2378.15"
    }
  ],
  "watch": [
    {
      "symbol": "RELIANCE",
      "name": "Reliance Industries",
      "gffi": 36.4,
      "action": "WATCH",
      "reason": "Moderate GFFI at ₹1412.55"
    },
    {
      "symbol": "ICICIBANK",
      "name": "ICICI Bank",
      "gffi": 36.8,
      "action": "WATCH",
      "reason": "Moderate GFFI at ₹1259.8"
    },
    {
      "symbol": "HINDUNILVR",
      "name": "Hindustan Unilever",
      "gffi": 36.8,
      "action": "WATCH",
      "reason": "Moderate GFFI at ₹2135.9"
    }
  ]
};

const indiaMarketData = {
  "nifty": 0,
  "sensex": 0,
  "nifty_change": 0,
  "sensex_change": 0
};

const crisisData = {
  "probability": 0,
  "lead_time_min": null,
  "lead_time_max": null,
  "lead_time_avg": null,
  "status": "NORMAL",
  "message": "Below crisis threshold"
};

const marketEfficiency = 65;