// Auto-generated by GFFI Bot
const countryData = [
    {flag: '🇺🇸', name: 'USA', gffi: 62.1, status: 'warning'},
    {flag: '🇩🇪', name: 'Germany', gffi: 68.4, status: 'success'},
    {flag: '🇫🇷', name: 'France', gffi: 63.5, status: 'warning'},
    {flag: '🇯🇵', name: 'Japan', gffi: 65.9, status: 'warning'},
    {flag: '🇬🇧', name: 'UK', gffi: 65.0, status: 'success'},
    {flag: '🇨🇳', name: 'China', gffi: 64.6, status: 'warning'},
    {flag: '🇮🇳', name: 'India', gffi: 64.7, status: 'success'},
    {flag: '🇧🇷', name: 'Brazil', gffi: 65.5, status: 'success'},
    {flag: '🇷🇺', name: 'Russia', gffi: 61.5, status: 'success'},
    {flag: '🇿🇦', name: 'S. Africa', gffi: 61.2, status: 'success'},
    {flag: '🇨🇦', name: 'Canada', gffi: 70.8, status: 'warning'},
    {flag: '🇮🇹', name: 'Italy', gffi: 62.5, status: 'warning'},
    {flag: '🇦🇺', name: 'Australia', gffi: 61.5, status: 'warning'},
    {flag: '🇰🇷', name: 'S. Korea', gffi: 61.2, status: 'success'},
    {flag: '🇸🇬', name: 'Singapore', gffi: 62.8, status: 'success'},
    {flag: '🇲🇽', name: 'Mexico', gffi: 61.5, status: 'warning'},
    {flag: '🇦🇷', name: 'Argentina', gffi: 63.2, status: 'warning'}
];

const globalGFFI = 63.5;
const updateDate = '11 Mar 2026';
const updateTime = '10:30 AM';

// Function to update dashboard
function updateDashboard() {
    // Update global GFFI
    document.getElementById('global-gffi').textContent = globalGFFI;
    document.getElementById('update-time').textContent = updateDate;
    document.getElementById('update-time-hm').textContent = updateTime;
    
    // Update country grid
    const countryGrid = document.getElementById('country-grid');
    if (countryGrid) {
        let html = '';
        countryData.forEach(country => {
            html += `
                <div class="country-card">
                    <div class="country-flag">${country.flag}</div>
                    <div class="country-name">${country.name}</div>
                    <div class="country-gffi">${country.gffi}</div>
                    <span class="country-status status-${country.status}">${country.status.toUpperCase()}</span>
                </div>
            `;
        });
        countryGrid.innerHTML = html;
    }
}

// Run when page loads
document.addEventListener('DOMContentLoaded', updateDashboard);
