// Auto-generated by GFFI Bot
const countryData = [
    {flag: '🇺🇸', name: 'USA', gffi: 62.1, status: 'warning'},
    {flag: '🇩🇪', name: 'Germany', gffi: 68.4, status: 'success'},
    {flag: '🇫🇷', name: 'France', gffi: 63.5, status: 'warning'},
    {flag: '🇯🇵', name: 'Japan', gffi: 65.9, status: 'warning'},
    {flag: '🇬🇧', name: 'UK', gffi: 65.0, status: 'success'},
    {flag: '🇨🇳', name: 'China', gffi: 64.6, status: 'warning'},
    {flag: '🇮🇳', name: 'India', gffi: 64.7, status: 'success'},
    {flag: '🇧🇷', name: 'Brazil', gffi: 65.5, status: 'success'},
    {flag: '🇷🇺', name: 'Russia', gffi: 61.5, status: 'success'},
    {flag: '🇿🇦', name: 'S. Africa', gffi: 61.2, status: 'success'},
    {flag: '🇨🇦', name: 'Canada', gffi: 70.8, status: 'warning'},
    {flag: '🇮🇹', name: 'Italy', gffi: 62.5, status: 'warning'},
    {flag: '🇦🇺', name: 'Australia', gffi: 61.5, status: 'warning'},
    {flag: '🇰🇷', name: 'S. Korea', gffi: 61.2, status: 'success'},
    {flag: '🇸🇬', name: 'Singapore', gffi: 62.8, status: 'success'},
    {flag: '🇲🇽', name: 'Mexico', gffi: 61.5, status: 'warning'},
    {flag: '🇦🇷', name: 'Argentina', gffi: 63.2, status: 'warning'}
];

const globalGFFI = 63.5;
const updateDate = '15 Mar 2026';
const updateTime = '11:00 AM';

// Sector data
const sectorData = [
    { name: 'Banking & Financials', gffi: 68.5, trend: 'up', stocks: ['HDFC Bank', 'ICICI Bank', 'SBI', 'Kotak Bank'] },
    { name: 'Information Technology', gffi: 58.2, trend: 'down', stocks: ['TCS', 'Infosys', 'HCL Tech', 'Wipro'] },
    { name: 'Pharmaceuticals', gffi: 55.8, trend: 'stable', stocks: ['Sun Pharma', 'Cipla', 'Dr Reddy', 'Divis Labs'] },
    { name: 'Automobile', gffi: 62.1, trend: 'up', stocks: ['Maruti', 'Tata Motors', 'M&M', 'Bajaj Auto'] },
    { name: 'Energy', gffi: 65.4, trend: 'up', stocks: ['Reliance', 'ONGC', 'BPCL', 'IOC'] },
    { name: 'FMCG', gffi: 52.3, trend: 'down', stocks: ['ITC', 'HUL', 'Britannia', 'Nestle'] },
    { name: 'Metals', gffi: 64.7, trend: 'up', stocks: ['Tata Steel', 'JSW Steel', 'Hindalco', 'Coal India'] },
    { name: 'Telecom', gffi: 59.5, trend: 'stable', stocks: ['Bharti Airtel', 'Reliance Jio', 'Vodafone Idea'] },
];

// Stock picks
const stockPicks = {
    safe: [
        { symbol: 'ITC', name: 'ITC Ltd', gffi: 52.3, action: 'BUY', reason: 'Low volatility, strong fundamentals' },
        { symbol: 'HUL', name: 'Hindustan Unilever', gffi: 53.1, action: 'BUY', reason: 'Defensive play, consistent returns' },
        { symbol: 'TCS', name: 'Tata Consultancy', gffi: 54.2, action: 'BUY', reason: 'Stable IT major, good dividends' },
        { symbol: 'CIPLA', name: 'Cipla Ltd', gffi: 54.8, action: 'BUY', reason: 'Pharma safe haven' },
        { symbol: 'BRITANNIA', name: 'Britannia', gffi: 55.1, action: 'BUY', reason: 'FMCG resilience' },
    ],
    risky: [
        { symbol: 'YESBANK', name: 'Yes Bank', gffi: 78.5, action: 'SELL', reason: 'High volatility, weak fundamentals' },
        { symbol: 'ADANIGREEN', name: 'Adani Green', gffi: 76.2, action: 'SELL', reason: 'Overvalued, high debt' },
        { symbol: 'VEDL', name: 'Vedanta', gffi: 74.3, action: 'SELL', reason: 'Commodity risk, high GFFI' },
        { symbol: 'IDEA', name: 'Vodafone Idea', gffi: 72.8, action: 'SELL', reason: 'High debt, negative outlook' },
        { symbol: 'ZOMATO', name: 'Zomato', gffi: 71.5, action: 'SELL', reason: 'Overvalued, profit concerns' },
    ],
    watch: [
        { symbol: 'RELIANCE', name: 'Reliance Ind', gffi: 62.5, action: 'WATCH', reason: 'Strong but expensive' },
        { symbol: 'HDFCBANK', name: 'HDFC Bank', gffi: 63.2, action: 'WATCH', reason: 'Quality but valuations high' },
        { symbol: 'INFY', name: 'Infosys', gffi: 59.8, action: 'WATCH', reason: 'IT momentum, but global risks' },
        { symbol: 'MARUTI', name: 'Maruti Suzuki', gffi: 61.4, action: 'WATCH', reason: 'Auto recovery play' },
        { symbol: 'TATAMOTORS', name: 'Tata Motors', gffi: 62.9, action: 'WATCH', reason: 'EV potential, debt concerns' },
    ]
};

// Render sector cards
function renderSectorAnalysis() {
    const sectorGrid = document.getElementById('sector-grid');
    if (!sectorGrid) return;
    
    let html = '';
    sectorData.forEach(sector => {
        let bgColor, textColor;
        if (sector.gffi >= 70) {
            bgColor = '#ffcccc'; textColor = '#990000';
        } else if (sector.gffi >= 65) {
            bgColor = '#fff3cd'; textColor = '#856404';
        } else if (sector.gffi >= 58) {
            bgColor = '#d4edda'; textColor = '#155724';
        } else {
            bgColor = '#cce5ff'; textColor = '#004085';
        }
        
        const trendIcon = sector.trend === 'up' ? '📈' : sector.trend === 'down' ? '📉' : '➡️';
        
        html += `
            <div class="sector-card" style="background: ${bgColor}; color: ${textColor};">
                <div class="sector-name">${sector.name} ${trendIcon}</div>
                <div class="sector-gffi">${sector.gffi.toFixed(1)}</div>
                <div class="sector-status">${sector.gffi >= 70 ? '🔴 HIGH' : sector.gffi >= 65 ? '🟠 ALERT' : sector.gffi >= 58 ? '🟡 WATCH' : '🟢 SAFE'}</div>
                <div style="font-size: 0.8rem; margin-top: 8px;">
                    <strong>Top Picks:</strong> ${sector.stocks.slice(0, 3).join(', ')}
                </div>
            </div>
        `;
    });
    
    sectorGrid.innerHTML = html;
}

// Render stock picks
function renderStockPicks() {
    const safeDiv = document.getElementById('safe-picks');
    if (safeDiv) {
        let html = '';
        stockPicks.safe.forEach(stock => {
            html += `
                <div class="stock-item">
                    <span class="stock-symbol">${stock.symbol}</span>
                    <span class="stock-gffi">${stock.gffi}</span>
                    <span class="stock-action buy">${stock.action}</span>
                </div>
                <div style="font-size: 0.8rem; color: #6c757d; margin-bottom: 5px;">${stock.reason}</div>
            `;
        });
        safeDiv.innerHTML = html;
    }
    
    const riskyDiv = document.getElementById('risky-picks');
    if (riskyDiv) {
        let html = '';
        stockPicks.risky.forEach(stock => {
            html += `
                <div class="stock-item">
                    <span class="stock-symbol">${stock.symbol}</span>
                    <span class="stock-gffi">${stock.gffi}</span>
                    <span class="stock-action sell">${stock.action}</span>
                </div>
                <div style="font-size: 0.8rem; color: #6c757d; margin-bottom: 5px;">${stock.reason}</div>
            `;
        });
        riskyDiv.innerHTML = html;
    }
    
    const watchDiv = document.getElementById('watch-picks');
    if (watchDiv) {
        let html = '';
        stockPicks.watch.forEach(stock => {
            html += `
                <div class="stock-item">
                    <span class="stock-symbol">${stock.symbol}</span>
                    <span class="stock-gffi">${stock.gffi}</span>
                    <span class="stock-action watch">${stock.action}</span>
                </div>
                <div style="font-size: 0.8rem; color: #6c757d; margin-bottom: 5px;">${stock.reason}</div>
            `;
        });
        watchDiv.innerHTML = html;
    }
}

// Main update function
function updateDashboard() {
    // Update global GFFI
    document.getElementById('global-gffi').textContent = globalGFFI;
    document.getElementById('update-time').textContent = updateDate;
    document.getElementById('update-time-hm').textContent = updateTime;
    
    // Update country grid
    const countryGrid = document.getElementById('country-grid');
    if (countryGrid) {
        let html = '';
        countryData.forEach(country => {
            html += `
                <div class="country-card">
                    <div class="country-flag">${country.flag}</div>
                    <div class="country-name">${country.name}</div>
                    <div class="country-gffi">${country.gffi}</div>
                    <span class="country-status status-${country.status}">${country.status.toUpperCase()}</span>
                </div>
            `;
        });
        countryGrid.innerHTML = html;
    }
    // ============================================
// INDIA MARKET DATA
// ============================================

// Real-time India market data
const indiaMarketData = {
    nifty: 77566,
    sensex: 77566,
    vix: 23.36,
    indiaGFFI: 64.7,
    advance: 850,
    decline: 1650,
    marketStatus: 'bearish',
    fearLevel: 'extreme'
};

// Sector performance data
const sectorPerformance = [
    { name: 'Banking', change: -2.3, status: 'bearish' },
    { name: 'IT', change: +0.5, status: 'bullish' },
    { name: 'Pharma', change: -0.2, status: 'neutral' },
    { name: 'Auto', change: -1.5, status: 'bearish' },
    { name: 'FMCG', change: +0.8, status: 'bullish' },
    { name: 'Energy', change: -1.8, status: 'bearish' },
    { name: 'Metals', change: -2.1, status: 'bearish' },
    { name: 'Realty', change: -0.5, status: 'neutral' }
];

// Update India market dashboard
function updateIndiaMarket() {
    // Update Nifty
    const niftyEl = document.getElementById('nifty-value');
    if (niftyEl) niftyEl.textContent = indiaMarketData.nifty.toLocaleString();
    
    const niftyChange = document.getElementById('nifty-change');
    if (niftyChange) {
        niftyChange.textContent = '-1.71%';
        niftyChange.className = 'card-change negative';
    }
    
    // Update Sensex
    const sensexEl = document.getElementById('sensex-value');
    if (sensexEl) sensexEl.textContent = indiaMarketData.sensex.toLocaleString();
    
    const sensexChange = document.getElementById('sensex-change');
    if (sensexChange) {
        sensexChange.textContent = '-1.71%';
        sensexChange.className = 'card-change negative';
    }
    
    // Update VIX
    const vixEl = document.getElementById('vix-value');
    if (vixEl) vixEl.textContent = indiaMarketData.vix.toFixed(2);
    
    const vixChange = document.getElementById('vix-change');
    if (vixChange) {
        vixChange.textContent = '+17.58%';
        vixChange.className = 'card-change negative';
    }
    
    // Update India GFFI
    const indiaGFFIEl = document.getElementById('india-gffi');
    if (indiaGFFIEl) indiaGFFIEl.textContent = indiaMarketData.indiaGFFI;
    
    const indiaStatus = document.getElementById('india-status');
    if (indiaStatus) {
        if (indiaMarketData.indiaGFFI >= 75) {
            indiaStatus.textContent = '🔴 CRITICAL';
            indiaStatus.style.color = '#dc3545';
        } else if (indiaMarketData.indiaGFFI >= 65) {
            indiaStatus.textContent = '🟠 ALERT';
            indiaStatus.style.color = '#fd7e14';
        } else if (indiaMarketData.indiaGFFI >= 58) {
            indiaStatus.textContent = '🟡 WATCH';
            indiaStatus.style.color = '#ffc107';
        } else {
            indiaStatus.textContent = '🟢 SUCCESS';
            indiaStatus.style.color = '#28a745';
        }
    }
    
    // Update market status
    const marketStatusEl = document.getElementById('market-status');
    if (marketStatusEl) {
        marketStatusEl.textContent = '🔴 BEARISH';
        marketStatusEl.style.color = '#dc3545';
    }
    
    const fearLevelEl = document.getElementById('fear-level');
    if (fearLevelEl) {
        fearLevelEl.textContent = '😱 EXTREME FEAR';
        fearLevelEl.style.color = '#dc3545';
    }
    
    const advDeclEl = document.getElementById('adv-decl');
    if (advDeclEl) {
        advDeclEl.textContent = `${indiaMarketData.advance} / ${indiaMarketData.decline}`;
    }
    
    // Update sector tags
    updateSectorTags();
}

// Update sector performance tags
function updateSectorTags() {
    const sectorTagsEl = document.getElementById('sector-tags');
    if (!sectorTagsEl) return;
    
    let html = '';
    sectorPerformance.forEach(sector => {
        let bgColor, textColor;
        if (sector.status === 'bullish') {
            bgColor = '#d4edda';
            textColor = '#155724';
        } else if (sector.status === 'bearish') {
            bgColor = '#f8d7da';
            textColor = '#721c24';
        } else {
            bgColor = '#fff3cd';
            textColor = '#856404';
        }
        
        const changeIcon = sector.change > 0 ? '▲' : '▼';
        const changeColor = sector.change > 0 ? '#155724' : '#721c24';
        
        html += `
            <span class="sector-tag" style="background: ${bgColor}; color: ${textColor};">
                ${sector.name} ${changeIcon} ${Math.abs(sector.change)}%
            </span>
        `;
    });
    
    sectorTagsEl.innerHTML = html;
}

// Add these function calls to updateDashboard()
function updateDashboard() {
    // ... existing code ...
    
    // Add this line at the end
    updateIndiaMarket();
}
    // Render new features
    renderSectorAnalysis();
    renderStockPicks();
}

// Run when page loads
document.addEventListener('DOMContentLoaded', updateDashboard);
