// Auto-generated by GFFI Bot on 2026-03-14 06:35:06
const countryData = [
  {
    "flag": "\ud83c\uddfa\ud83c\uddf8",
    "name": "USA",
    "gffi": 62.1,
    "status": "warning"
  },
  {
    "flag": "\ud83c\uddee\ud83c\uddf3",
    "name": "India",
    "gffi": 64.7,
    "status": "success"
  },
  {
    "flag": "\ud83c\udde9\ud83c\uddea",
    "name": "Germany",
    "gffi": 68.4,
    "status": "success"
  }
];
const globalGFFI = 65.1;
const updateDate = '14 Mar 2026';
const updateTime = '06:35 AM';

// Function to update dashboard
function updateDashboard() {
    document.getElementById('global-gffi')?.textContent = globalGFFI;
    document.getElementById('update-time')?.textContent = updateDate;
    document.getElementById('update-time-hm')?.textContent = updateTime;
    
    const countryGrid = document.getElementById('country-grid');
    if (countryGrid) {
        let html = '';
        countryData.forEach(country => {
            html += `
                <div class="country-card">
                    <div class="country-flag">${country.flag}</div>
                    <div class="country-name">${country.name}</div>
                    <div class="country-gffi">${country.gffi}</div>
                    <span class="country-status status-${country.status}">${country.status.toUpperCase()}</span>
                </div>
            `;
        });
        countryGrid.innerHTML = html;
    }
}

// Run when page loads
document.addEventListener('DOMContentLoaded', updateDashboard);
