#!/usr/bin/env python3
"""
GFFI Daily Update Script - FORCE UPDATE VERSION
"""

import yfinance as yf
import numpy as np
from datetime import datetime
import json
import sys
import os

print("="*60)
print("🚀 GFFI UPDATE SCRIPT - FORCE UPDATE VERSION")
print("="*60)
print(f"📅 Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print(f"📂 Current directory: {os.getcwd()}")

# ============================================
# CONFIGURATION
# ============================================

COUNTRIES = [
    {'code': 'US', 'name': 'USA', 'flag': '🇺🇸', 'ticker': '^GSPC'},
    {'code': 'Germany', 'name': 'Germany', 'flag': '🇩🇪', 'ticker': '^GDAXI'},
    {'code': 'France', 'name': 'France', 'flag': '🇫🇷', 'ticker': '^FCHI'},
    {'code': 'Japan', 'name': 'Japan', 'flag': '🇯🇵', 'ticker': '^N225'},
    {'code': 'UK', 'name': 'UK', 'flag': '🇬🇧', 'ticker': '^FTSE'},
    {'code': 'China', 'name': 'China', 'flag': '🇨🇳', 'ticker': '000001.SS'},
    {'code': 'India', 'name': 'India', 'flag': '🇮🇳', 'ticker': '^NSEI'},
    {'code': 'Brazil', 'name': 'Brazil', 'flag': '🇧🇷', 'ticker': '^BVSP'},
    {'code': 'Russia', 'name': 'Russia', 'flag': '🇷🇺', 'ticker': 'IMOEX.ME'},
    {'code': 'SouthAfrica', 'name': 'S. Africa', 'flag': '🇿🇦', 'ticker': '^JN0U.JO'},
    {'code': 'Canada', 'name': 'Canada', 'flag': '🇨🇦', 'ticker': '^GSPTSE'},
    {'code': 'Italy', 'name': 'Italy', 'flag': '🇮🇹', 'ticker': 'FTSEMIB.MI'},
    {'code': 'Australia', 'name': 'Australia', 'flag': '🇦🇺', 'ticker': '^AXJO'},
    {'code': 'SouthKorea', 'name': 'S. Korea', 'flag': '🇰🇷', 'ticker': '^KS11'},
    {'code': 'Singapore', 'name': 'Singapore', 'flag': '🇸🇬', 'ticker': '^STI'},
    {'code': 'Mexico', 'name': 'Mexico', 'flag': '🇲🇽', 'ticker': '^MXX'},
    {'code': 'Argentina', 'name': 'Argentina', 'flag': '🇦🇷', 'ticker': '^MERV'},
]

# Fallback data in case API fails
FALLBACK_DATA = [
    {'flag': '🇺🇸', 'name': 'USA', 'gffi': 62.1, 'status': 'warning'},
    {'flag': '🇩🇪', 'name': 'Germany', 'gffi': 68.4, 'status': 'success'},
    {'flag': '🇫🇷', 'name': 'France', 'gffi': 63.5, 'status': 'warning'},
    {'flag': '🇯🇵', 'name': 'Japan', 'gffi': 65.9, 'status': 'warning'},
    {'flag': '🇬🇧', 'name': 'UK', 'gffi': 65.0, 'status': 'success'},
    {'flag': '🇨🇳', 'name': 'China', 'gffi': 64.6, 'status': 'warning'},
    {'flag': '🇮🇳', 'name': 'India', 'gffi': 64.7, 'status': 'success'},
    {'flag': '🇧🇷', 'name': 'Brazil', 'gffi': 65.5, 'status': 'success'},
    {'flag': '🇷🇺', 'name': 'Russia', 'gffi': 61.5, 'status': 'success'},
    {'flag': '🇿🇦', 'name': 'S. Africa', 'gffi': 61.2, 'status': 'success'},
    {'flag': '🇨🇦', 'name': 'Canada', 'gffi': 70.8, 'status': 'warning'},
    {'flag': '🇮🇹', 'name': 'Italy', 'gffi': 62.5, 'status': 'warning'},
    {'flag': '🇦🇺', 'name': 'Australia', 'gffi': 61.5, 'status': 'warning'},
    {'flag': '🇰🇷', 'name': 'S. Korea', 'gffi': 61.2, 'status': 'success'},
    {'flag': '🇸🇬', 'name': 'Singapore', 'gffi': 62.8, 'status': 'success'},
    {'flag': '🇲🇽', 'name': 'Mexico', 'gffi': 61.5, 'status': 'warning'},
    {'flag': '🇦🇷', 'name': 'Argentina', 'gffi': 63.2, 'status': 'warning'},
]

def get_status(gffi):
    if gffi >= 75:
        return 'critical'
    elif gffi >= 65:
        return 'alert'
    elif gffi >= 58:
        return 'warning'
    else:
        return 'success'

def fetch_country_data(country):
    """Fetch data for a country"""
    try:
        print(f"   📊 Fetching {country['name']}...", end=' ')
        ticker = yf.Ticker(country['ticker'])
        hist = ticker.history(period="1d")
        
        if hist.empty:
            print(f"⚠️ No data")
            return None
        
        price = hist['Close'].iloc[-1]
        print(f"✅ Price: {price:.2f}")
        
        # Simple GFFI based on random for now (replace with your logic)
        gffi = 60 + np.random.normal(0, 5)
        gffi = max(40, min(85, gffi))
        
        return {
            'flag': country['flag'],
            'name': country['name'],
            'gffi': round(gffi, 1),
            'status': get_status(gffi)
        }
    except Exception as e:
        print(f"❌ Error: {e}")
        return None

def main():
    print("\n📡 Fetching live data...")
    
    country_data = []
    success_count = 0
    
    for country in COUNTRIES:
        data = fetch_country_data(country)
        if data:
            country_data.append(data)
            success_count += 1
    
    print(f"\n✅ Successfully fetched {success_count}/{len(COUNTRIES)} countries")
    
    # If no data fetched, use fallback
    if not country_data:
        print("⚠️ No data fetched! Using fallback data...")
        country_data = FALLBACK_DATA
        global_gffi = 63.5
    else:
        # Calculate global average from fetched data
        gffi_values = [c['gffi'] for c in country_data]
        global_gffi = sum(gffi_values) / len(gffi_values)
    
    # Update script.js
    now = datetime.now()
    js_content = f"""// Auto-generated by GFFI Bot on {now.strftime('%Y-%m-%d %H:%M:%S')}
const countryData = {json.dumps(country_data, indent=2)};
const globalGFFI = {global_gffi:.1f};
const updateDate = '{now.strftime("%d %b %Y")}';
const updateTime = '{now.strftime("%I:%M %p")}';

// Function to update dashboard
function updateDashboard() {{
    document.getElementById('global-gffi').textContent = globalGFFI;
    document.getElementById('update-time').textContent = updateDate;
    document.getElementById('update-time-hm').textContent = updateTime;
    
    const countryGrid = document.getElementById('country-grid');
    if (countryGrid) {{
        let html = '';
        countryData.forEach(country => {{
            html += `
                <div class="country-card">
                    <div class="country-flag">${{country.flag}}</div>
                    <div class="country-name">${{country.name}}</div>
                    <div class="country-gffi">${{country.gffi}}</div>
                    <span class="country-status status-${{country.status}}">${{country.status.toUpperCase()}}</span>
                </div>
            `;
        }});
        countryGrid.innerHTML = html;
    }}
}}

// Run when page loads
document.addEventListener('DOMContentLoaded', updateDashboard);
"""
    
    # Write to file
    with open('script.js', 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print(f"\n✅ script.js updated with {len(country_data)} countries")
    print(f"🌍 Global GFFI: {global_gffi:.1f}")
    print("="*60)

if __name__ == "__main__":
    main()
