#!/usr/bin/env python3
"""
GFFI Daily Update Script - FIXED VERSION
"""

import yfinance as yf
import numpy as np
from datetime import datetime
import json
import traceback

COUNTRIES = [
    {'code': 'US', 'name': 'USA', 'flag': '🇺🇸', 'ticker': '^GSPC'},
    {'code': 'Germany', 'name': 'Germany', 'flag': '🇩🇪', 'ticker': '^GDAXI'},
    {'code': 'France', 'name': 'France', 'flag': '🇫🇷', 'ticker': '^FCHI'},
    {'code': 'Japan', 'name': 'Japan', 'flag': '🇯🇵', 'ticker': '^N225'},
    {'code': 'UK', 'name': 'UK', 'flag': '🇬🇧', 'ticker': '^FTSE'},
    {'code': 'China', 'name': 'China', 'flag': '🇨🇳', 'ticker': '000001.SS'},
    {'code': 'India', 'name': 'India', 'flag': '🇮🇳', 'ticker': '^NSEI'},
    {'code': 'Brazil', 'name': 'Brazil', 'flag': '🇧🇷', 'ticker': '^BVSP'},
    {'code': 'Russia', 'name': 'Russia', 'flag': '🇷🇺', 'ticker': 'IMOEX.ME'},
    {'code': 'SouthAfrica', 'name': 'S. Africa', 'flag': '🇿🇦', 'ticker': '^JN0U.JO'},
    {'code': 'Canada', 'name': 'Canada', 'flag': '🇨🇦', 'ticker': '^GSPTSE'},
    {'code': 'Italy', 'name': 'Italy', 'flag': '🇮🇹', 'ticker': 'FTSEMIB.MI'},
    {'code': 'Australia', 'name': 'Australia', 'flag': '🇦🇺', 'ticker': '^AXJO'},
    {'code': 'SouthKorea', 'name': 'S. Korea', 'flag': '🇰🇷', 'ticker': '^KS11'},
    {'code': 'Singapore', 'name': 'Singapore', 'flag': '🇸🇬', 'ticker': '^STI'},
    {'code': 'Mexico', 'name': 'Mexico', 'flag': '🇲🇽', 'ticker': '^MXX'},
    {'code': 'Argentina', 'name': 'Argentina', 'flag': '🇦🇷', 'ticker': '^MERV'},
]

def get_status(gffi):
    if gffi >= 75:
        return 'critical', '🔴 CRITICAL'
    elif gffi >= 65:
        return 'alert', '🟠 ALERT'
    elif gffi >= 58:
        return 'warning', '🟡 WATCH'
    else:
        return 'success', '🟢 NORMAL'

def calculate_gffi_from_price(price_history):
    """Calculate GFFI from price history"""
    if len(price_history) < 10:
        return 60 + np.random.normal(0, 2)
    
    # Simple volatility-based GFFI
    returns = np.diff(price_history) / price_history[:-1] * 100
    volatility = np.std(returns)
    gffi = 50 + volatility * 2
    return np.clip(gffi, 40, 85)

def fetch_country_data(country):
    """Fetch data for a country"""
    try:
        print(f"   Fetching {country['name']}...")
        ticker = yf.Ticker(country['ticker'])
        
        # Get 1 month data
        hist = ticker.history(period="1mo")
        
        if hist.empty:
            print(f"   ⚠️ No data for {country['name']}, using random")
            gffi = 60 + np.random.normal(0, 5)
        else:
            prices = hist['Close'].values
            gffi = calculate_gffi_from_price(prices)
            print(f"   ✅ {country['name']}: GFFI={gffi:.1f}")
        
        status_code, status_text = get_status(gffi)
        
        return {
            'flag': country['flag'],
            'name': country['name'],
            'gffi': round(gffi, 1),
            'status': status_code,
        }
    except Exception as e:
        print(f"   ❌ Error fetching {country['name']}: {e}")
        # Return fallback data
        return {
            'flag': country['flag'],
            'name': country['name'],
            'gffi': round(60 + np.random.normal(0, 5), 1),
            'status': 'warning',
        }

def update_script_js(country_data, global_gffi):
    """Update script.js with new data"""
    now = datetime.now()
    
    js_content = f"""// Auto-generated by GFFI Bot on {now.strftime('%Y-%m-%d %H:%M:%S')}
const countryData = {json.dumps(country_data, indent=2)};
const globalGFFI = {global_gffi:.1f};
const updateDate = '{now.strftime("%d %b %Y")}';
const updateTime = '{now.strftime("%I:%M %p")}';

// Function to update dashboard
function updateDashboard() {{
    document.getElementById('global-gffi').textContent = globalGFFI;
    document.getElementById('update-time').textContent = updateDate;
    document.getElementById('update-time-hm').textContent = updateTime;
    
    const countryGrid = document.getElementById('country-grid');
    if (countryGrid) {{
        let html = '';
        countryData.forEach(country => {{
            html += `
                <div class="country-card">
                    <div class="country-flag">${{country.flag}}</div>
                    <div class="country-name">${{country.name}}</div>
                    <div class="country-gffi">${{country.gffi}}</div>
                    <span class="country-status status-${{country.status}}">${{country.status.toUpperCase()}}</span>
                </div>
            `;
        }});
        countryGrid.innerHTML = html;
    }}
}}

// Run when page loads
document.addEventListener('DOMContentLoaded', updateDashboard);
"""
    
    with open('script.js', 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print(f"✅ script.js updated with {len(country_data)} countries")
    return True

def main():
    print("\n" + "="*60)
    print("🚀 GFFI UPDATE SCRIPT - STARTED")
    print("="*60)
    print(f"📅 Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    country_data = []
    
    for country in COUNTRIES:
        data = fetch_country_data(country)
        if data:
            country_data.append(data)
    
    if not country_data:
        print("❌ No data fetched!")
        return
    
    # Calculate global average
    gffi_values = [c['gffi'] for c in country_data]
    global_gffi = sum(gffi_values) / len(gffi_values)
    
    print(f"\n🌍 Global GFFI: {global_gffi:.1f}")
    
    # Update script.js
    if update_script_js(country_data, global_gffi):
        print("✅ Update successful!")
    else:
        print("❌ Update failed!")
    
    print("="*60)

if __name__ == "__main__":
    main()
