#!/usr/bin/env python3
"""
GFFI Daily Update Script
"""

import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime
import json

COUNTRIES = [
    {'code': 'US', 'name': 'USA', 'flag': '🇺🇸', 'ticker': '^GSPC'},
    {'code': 'Germany', 'name': 'Germany', 'flag': '🇩🇪', 'ticker': '^GDAXI'},
    {'code': 'France', 'name': 'France', 'flag': '🇫🇷', 'ticker': '^FCHI'},
    {'code': 'Japan', 'name': 'Japan', 'flag': '🇯🇵', 'ticker': '^N225'},
    {'code': 'UK', 'name': 'UK', 'flag': '🇬🇧', 'ticker': '^FTSE'},
    {'code': 'China', 'name': 'China', 'flag': '🇨🇳', 'ticker': '000001.SS'},
    {'code': 'India', 'name': 'India', 'flag': '🇮🇳', 'ticker': '^NSEI'},
    {'code': 'Brazil', 'name': 'Brazil', 'flag': '🇧🇷', 'ticker': '^BVSP'},
    {'code': 'Russia', 'name': 'Russia', 'flag': '🇷🇺', 'ticker': 'IMOEX.ME'},
    {'code': 'SouthAfrica', 'name': 'S. Africa', 'flag': '🇿🇦', 'ticker': '^JN0U.JO'},
    {'code': 'Canada', 'name': 'Canada', 'flag': '🇨🇦', 'ticker': '^GSPTSE'},
    {'code': 'Italy', 'name': 'Italy', 'flag': '🇮🇹', 'ticker': 'FTSEMIB.MI'},
    {'code': 'Australia', 'name': 'Australia', 'flag': '🇦🇺', 'ticker': '^AXJO'},
    {'code': 'SouthKorea', 'name': 'S. Korea', 'flag': '🇰🇷', 'ticker': '^KS11'},
    {'code': 'Singapore', 'name': 'Singapore', 'flag': '🇸🇬', 'ticker': '^STI'},
    {'code': 'Mexico', 'name': 'Mexico', 'flag': '🇲🇽', 'ticker': '^MXX'},
    {'code': 'Argentina', 'name': 'Argentina', 'flag': '🇦🇷', 'ticker': '^MERV'},
]

def calculate_entropy(prices, window=60, bins=10):
    if len(prices) < window:
        return 0.5
    recent_prices = prices[-window:]
    returns = np.diff(recent_prices) / recent_prices[:-1] * 100
    hist, _ = np.histogram(returns, bins=bins)
    probs = hist / hist.sum()
    probs = probs[probs > 0]
    if len(probs) > 0:
        entropy = -np.sum(probs * np.log(probs))
        max_entropy = np.log(bins)
        entropy = entropy / max_entropy
    else:
        entropy = 0.5
    return entropy

def get_status(gffi):
    if gffi >= 75:
        return 'critical', '🔴 CRITICAL'
    elif gffi >= 65:
        return 'alert', '🟠 ALERT'
    elif gffi >= 58:
        return 'warning', '🟡 WATCH'
    else:
        return 'success', '🟢 NORMAL'

def fetch_country_data(country):
    try:
        ticker = yf.Ticker(country['ticker'])
        hist = ticker.history(period="3mo")
        if hist.empty:
            return None
        prices = hist['Close'].values
        entropy = calculate_entropy(prices)
        capital_ratio = 14.5
        gffi = (entropy / capital_ratio) * 1000
        status_code, status_text = get_status(gffi)
        return {
            'flag': country['flag'],
            'name': country['name'],
            'gffi': round(gffi, 1),
            'status': status_code,
            'status_text': status_text,
        }
    except:
        return None

def update_script_js(country_data, global_gffi):
    now = datetime.now()
    country_data_json = []
    for c in country_data:
        if c:
            country_data_json.append({
                'name': c['name'],
                'flag': c['flag'],
                'gffi': c['gffi'],
                'status': c['status']
            })
    
    js_content = f"""// Auto-generated by GFFI Bot on {now.strftime('%Y-%m-%d %H:%M:%S')}
const countryData = {json.dumps(country_data_json, indent=2)};
const globalGFFI = {global_gffi};
const globalStatus = '{get_status(global_gffi)[1]}';
const updateDate = '{now.strftime("%d %b %Y")}';
const updateTime = '{now.strftime("%I:%M %p")}';
"""
    
    with open('script.js', 'w', encoding='utf-8') as f:
        f.write(js_content)
    print("✅ script.js updated")

def main():
    print("🚀 Updating GFFI data...")
    country_data = []
    for country in COUNTRIES:
        print(f"📊 {country['name']}...")
        data = fetch_country_data(country)
        if data:
            country_data.append(data)
    
    gffi_values = [c['gffi'] for c in country_data if c]
    global_gffi = round(sum(gffi_values) / len(gffi_values), 1) if gffi_values else 63.5
    
    update_script_js(country_data, global_gffi)
    print("✅ Update complete!")

if __name__ == "__main__":
    main()
