#!/usr/bin/env python3
import yfinance as yf
import numpy as np
from datetime import datetime
import json
import os

print("🚀 GFFI Update Script Started")
print(f"Current directory: {os.getcwd()}")

# Sample data for testing
country_data = [
    {'flag': '🇺🇸', 'name': 'USA', 'gffi': 62.1, 'status': 'warning'},
    {'flag': '🇮🇳', 'name': 'India', 'gffi': 64.7, 'status': 'success'},
    {'flag': '🇩🇪', 'name': 'Germany', 'gffi': 68.4, 'status': 'success'},
]

# Calculate global average
global_gffi = sum(c['gffi'] for c in country_data) / len(country_data)

# Update script.js
js_content = f"""// Auto-generated by GFFI Bot on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
const countryData = {json.dumps(country_data, indent=2)};
const globalGFFI = {global_gffi:.1f};
const updateDate = '{datetime.now().strftime("%d %b %Y")}';
const updateTime = '{datetime.now().strftime("%I:%M %p")}';

// Function to update dashboard
function updateDashboard() {{
    document.getElementById('global-gffi')?.textContent = globalGFFI;
    document.getElementById('update-time')?.textContent = updateDate;
    document.getElementById('update-time-hm')?.textContent = updateTime;
    
    const countryGrid = document.getElementById('country-grid');
    if (countryGrid) {{
        let html = '';
        countryData.forEach(country => {{
            html += `
                <div class="country-card">
                    <div class="country-flag">${{country.flag}}</div>
                    <div class="country-name">${{country.name}}</div>
                    <div class="country-gffi">${{country.gffi}}</div>
                    <span class="country-status status-${{country.status}}">${{country.status.toUpperCase()}}</span>
                </div>
            `;
        }});
        countryGrid.innerHTML = html;
    }}
}}

// Run when page loads
document.addEventListener('DOMContentLoaded', updateDashboard);
"""

# Write to file
with open('script.js', 'w', encoding='utf-8') as f:
    f.write(js_content)

print("✅ script.js updated successfully")
print(f"🌍 Global GFFI: {global_gffi:.1f}")
# Charts data generation
def generate_charts_data():
    """Generate random walk data for last 30 days"""
    import random
    import numpy as np
    
    # Start from current GFFI
    current = global_gffi
    data = []
    
    # Generate realistic random walk
    for i in range(30):
        change = random.uniform(-0.5, 0.5)
        current += change
        # Keep within reasonable range
        current = max(58, min(72, current))
        data.append(round(current, 1))
    
    return data[::-1]  # Reverse to show oldest first

# In update_script_js function, add this:
def update_script_js(country_data, global_gffi):
    # ... existing code ...
    
    # Generate charts data
    charts_data = generate_charts_data()
    
    js_content += f"""
// Charts data (auto-generated)
const chartTrendData = {charts_data};
const chartDates = {[f"'{d}'" for d in dates]};
"""
    
    # ... rest of the code ...
